# Generated by Django 3.1.7 on 2021-07-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_post_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
